name: Maven Test and Docker Build
# Made nov 17 2024

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# These actions use hash pinning for increased security
#
#https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions


jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4.2.1 oct 7 2024

      # Step 2: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a #v4.2.1 oct 22 2024
        with:
          path: |
            ~/.m2/repository
            target
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      # Step 3: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b #v4.5.0 oct 21 2024
        with:
          java-version: "21"
          distribution: "temurin"

      # Step 4: Run Maven tests
      - name: Run Maven tests
        run: mvn test

  docker-build:
    runs-on: ubuntu-latest
    needs: test-build

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4.2.1 oct 7 2024

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 #v3.7.1 oct 4 2024

      # Step 3: Build Backend Docker Image
      - name: Build Backend Image
        run: |
          docker build -t backend:latest ./

      # Step 4: Build Frontend Docker Image
      - name: Build Frontend Image
        run: |
          docker build -t frontend:latest ./vue
